### ISSUE TITLE
Baltop updater is broken

### ISSUE THREAD

**Issue by OfficialTheosis** [lokka30/PhantomEconomy#46]
Before I start with this issue, I want to say that I love this plugin so far and think it's heavily underrated. I couldn't find a single up-to-date economy plugin that is as highly configurable and well documented yet simple as this one.

This is the only issue I've encountered with it so far. I'm pretty sure this wasn't happening when I first installed the plugin, but it's happening now, even after deleting the folder that the plugin generates (to make sure the issue wasn't related to my configurations).

The issue is the baltop updater - when my server starts, an error is thrown in console. As well as this, /baltop doesn't display any player names and their balances; only the header and "no players left to display" message.

This is the error in console:
![PhantomEconomy Error](https://user-images.githubusercontent.com/26799016/83626864-fa81be00-a58d-11ea-8ebc-dc89cb7fcfa5.png)

Thank you for this plugin and I really hope you keep it updated and maintained for the foreseeable future!

**Comment by lokka30** [comment]
Cheers for the kind words and descriptive report on the issue. 😁 

It's a known issue;
Unfortunately I have no idea how the baltop updater code even works (I didn't make it, a user offered it from their plugin), so I have completely given up on fixing it. I don't know how the error appears in the first place. Running it on my own test server (just me online, not an actual server where most bugs appear) I haven't experienced this issue for months.

Unfortunately I can't offer a solution until PhantomEconomy v2 comes out (which will be a long time in the future) as the data storage system will switch from JSON to SQL (which will also make baltop lookups so much easier and readable). 

I'd point you to -

- if you don't mind disabling the baltop updater, head to the settings file, the option to disable the baltop update task is near the bottom
- if you require baltop, then i'd suggest finding a different plugin if you can. I can't find any competitor plugins with similar features for you unfortunately (which is why I made this 😄), so I won't be able to assist you in that search.

Hope you have a great day.

**Comment by OfficialTheosis** [comment]
I guess that's fair enough. I'll just disable baltop for now until PhantomEconomy v2 comes out.

How will we know when it comes out?

**Comment by lokka30** [comment]
> 
> 
> I guess that's fair enough. I'll just disable baltop for now until PhantomEconomy v2 comes out.
> 
> How will we know when it comes out?

Absolutely no idea, you'll need to keep an eye on resource alerts on Spigot. It won't be any time soon, I have *a lot* of things happening in life, so I can't work on it right now.

**Comment by lokka30** [comment]
Hey @TheosisOfficial, I believe I have traced the exact spot where this error is occuring, and I am working on a repair method for it.

This issue should be caused by a user in the `data.json` file not having a balance set in it.

My guess is that this issue is caused by older versions of the plugin not saving the default balance to disk when they first join.

**Comment by OfficialTheosis** [comment]
> Hey @TheosisOfficial, I believe I have traced the exact spot where this error is occuring, and I am working on a repair method for it.
> 
> This issue should be caused by a user in the `data.json` file not having a balance set in it.
> 
> My guess is that this issue is caused by older versions of the plugin not saving the default balance to disk when they first join.

That's great, hope it's an easy fix!

**Comment by lokka30** [comment]
@TheosisOfficial did the update manage to fix the issue?

**Comment by OfficialTheosis** [comment]
Yeah, seems to be working now! :)

**Comment by lokka30** [comment]
> Yeah, seems to be working now! :)

Thanks a lot Theo!
