### ISSUE TITLE
Plugins that ask for formatted balances are receiving null via the current handling of vault.

### ISSUE THREAD

**Issue by LlmDl** [lokka30/PhantomEconomy#6]
As per the ticket on the Towny tracker, specifically the comment here; https://github.com/TownyAdvanced/Towny/issues/3732#issuecomment-593161119

When a plugin such as Towny asks for the formatted balance PhantomEconomy is returning null.

**Comment by dielfrag13** [comment]
a `return String.format("$%d", amount);` should do it :)

**Comment by lokka30** [comment]
Thank you for the report. Will look into this now.
Thanks for the recommendation @dielfrag13

**Comment by lokka30** [comment]
It seems the reason that the economy transaction was prevented is because Towny was trying to charge the player $0. When creating the checks in PhEcon, I thought other plugins wouldn't charge $0 or cancel the Vault transaction if so.
I'll update the plugin now to support charging players $0 and look at formatting the balances.

**Comment by dielfrag13** [comment]
Sounds good! Thank you for looking into this-- it's very much appreciated!

**Comment by lokka30** [comment]
I just pushed a commit which might fix the issues stated here. I will soon link the plugin's pre-release jar file. Would you be willing to test it? (not on a public server in case the plugin is unstable)

**Comment by lokka30** [comment]
The password is PhantomEconomy.
https://easyupload.io/8l19ec
Edit: I should note that the settings file was updated to allow the formatting.
Should I do formatting like '25 dollars' and '1 dollar' or '$25' and '$1'?

**Comment by dielfrag13** [comment]
Absolutely! I looked at your code and what you have included there should take care of it, but I'll give it a test run now and let you know of the results. Personally, I'm about the $25 and $1 life a bit more than "25 dollars" and "1 dollar," but it's not super important to me so I say do what your heart tells you is best 😉

**Comment by dielfrag13** [comment]
Alternatively, you could even leave that up to the user. you could have entries in your config file that say something like

`currencyPrefix=[user puts what symbol they want here]`
`currencyPostfix=[user puts name of currency they want here]`

and then do something in your public String format method like this:


```
    public String format(double amount) {
        if (amount == 1) { //Singular format.
            return String.format("%s%s %s",getCurrencyPrefix(), amount, getCurrencyPostfix());
        } else { //Plural format.
            return String.format("%s%s %ss", getCurrencyPrefix(), amount, getCurrencyPostfix());
        }
    }
```


That would give users the flexibility of being able to do whatever they want. Euros, dollars, waffles, whatever-- each with their own customized symbol. And you wouldn't need an extra method for singular or plural strings; the extra 's' at the end of the last %s token on the plural format bracket would take care of it. You could have a comment above the entries in the config file telling users to leave the corresponding setting blank if they didn't want a currency prefix or a postfix and the above code should work because it'd just insert an empty string into the prefix or postfix print tokens. How about that?

**Comment by dielfrag13** [comment]
Good news-- your change fixed it! 

![image](https://user-images.githubusercontent.com/11789604/75645041-c058f700-5c01-11ea-9917-0d18b9438f82.png)

Don't forget to put your space in between the %s tokens though 😉

**Comment by lokka30** [comment]
> 
> 
> Absolutely! I looked at your code and what you have included there should take care of it, but I'll give it a test run now and let you know of the results. Personally, I'm about the $25 and $1 life a bit more than "25 dollars" and "1 dollar," but it's not super important to me so I say do what your heart tells you is best 😉

brilliant - might make this a config option :) i'm also for the $.

> 
> 
> Good news-- your change fixed it!
> 
> ![image](https://user-images.githubusercontent.com/11789604/75645041-c058f700-5c01-11ea-9917-0d18b9438f82.png)
> 
> Don't forget to put your space in between the %s tokens though 😉

that's a massive relief to hear. thank you very much for testing it. will add a space too :)

issue will be fixed to the public in an upcoming release.

**Comment by lokka30** [comment]
Oops, shouldn'tve closed an issue that hasn't been proven fixed.

Here's the new jar, does it work properly too?
Once again, could be unstable, please don't use on a public server:

Note: settings.yml was updated.
https://easyupload.io/7diujg
Pass: PhantomEconomy

**Comment by dielfrag13** [comment]
My pleasure!

![image](https://user-images.githubusercontent.com/11789604/75737992-4f2b4980-5cbe-11ea-8d1c-f839795b82ca.png)

Looks like it's working perfectly :) Thank you so much for throwing in a fix

**Comment by lokka30** [comment]
> 
> 
> My pleasure!
> 
> ![image](https://user-images.githubusercontent.com/11789604/75737992-4f2b4980-5cbe-11ea-8d1c-f839795b82ca.png)
> 
> Looks like it's working perfectly :) Thank you so much for throwing in a fix

You beauty! Will release an update to the public shortly. Massive thanks to both of you for assisting me in resolving these problems.
